### ISSUE TITLE
Todolist SpringMVC - update todo issue

### ISSUE THREAD

**Issue by benas** [benas/todolist-mvc#1]
When I try to update a Todo, I get HTTP error 400.

**Comment by mrsargsyan** [comment]
any updates on this?

**Comment by anwaralam** [comment]
add setter in Todo model class 
public void setId(long id) {
 this.id = id;
}

**Comment by fmbenhassine** [comment]
Closing this as the repo will be archived, see https://github.com/benas/todolist-mvc#project-status.
