### ISSUE TITLE
Question on contribution

### ISSUE THREAD

**Issue by greenlaw110** [benas/todolist-mvc#11]
@benas Firstly thanks for the project and nice playground for framework authors to show their baby.

In terms of contribution can I ask a few questions?

1. Should I restricted to Spring based core?
2. Can I use other database solution e.g. MongoDB?
3. Is JSP the mandatory? Can I use other templating solution?
4. Can I submit a solution which does not use server rendering page at all?

**Comment by benas** [comment]
Hi, thank you!

> 1. Should I restricted to Spring based core?

No, the core is not the main goal of the project. It could be some static services with in memory HashMap for data

> 2. Can I use other database solution e.g. MongoDB?

Sure

>3. Is JSP the mandatory? Can I use other templating solution?

No, I was planning to add thymeleaf but lacking time to add it

> 4. Can I submit a solution which does not use server rendering page at all?

Please do it in your fork. Not sure I'll have time to maintain this project anymore. I may  add a notice in the readme for this.

Kind regards
Mahmoud

**Comment by greenlaw110** [comment]
Actually I've created one following [TodoBackend](http://www.todobackend.com) and submitted [the pull request](https://github.com/TodoBackend/todo-backend-site/pull/127) to them

https://github.com/greenlaw110/todomvc-act

**Comment by fmbenhassine** [comment]
Closing this as the repo will be archived, see https://github.com/benas/todolist-mvc#project-status.
