### ISSUE TITLE
Blank page after opening localhost:8080/

### ISSUE THREAD

**Issue by 007divyachawla** [benas/todolist-mvc#12]
After running cd todolist-web-springmvc && mvn tomcat7:run it is showing INFO: Starting ProtocolHandler ["http-bio-8080"] and after moving to URL localhost:8080/ i am seeing a blank page.

**Comment by fmbenhassine** [comment]
Closing this as the repo will be archived, see https://github.com/benas/todolist-mvc#project-status.
